
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1055:Uri return values should not be strings", Scope = "member", Target = "~M:Amazon.CloudFront.AmazonCloudFrontUrlSigner.GetCannedSignedURL(Amazon.CloudFront.AmazonCloudFrontUrlSigner.Protocol,System.String,System.IO.FileSystemInfo,System.String,System.String,System.DateTime)~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1055:Uri return values should not be strings", Scope = "member", Target = "~M:Amazon.CloudFront.AmazonCloudFrontUrlSigner.GetCannedSignedURL(Amazon.CloudFront.AmazonCloudFrontUrlSigner.Protocol,System.String,System.IO.TextReader,System.String,System.String,System.DateTime)~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1055:Uri return values should not be strings", Scope = "member", Target = "~M:Amazon.CloudFront.AmazonCloudFrontUrlSigner.GetCannedSignedURL(System.String,System.IO.TextReader,System.String,System.DateTime)~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1055:Uri return values should not be strings", Scope = "member", Target = "~M:Amazon.CloudFront.AmazonCloudFrontUrlSigner.GetCustomSignedURL(Amazon.CloudFront.AmazonCloudFrontUrlSigner.Protocol,System.String,System.IO.FileSystemInfo,System.String,System.String,System.DateTime,System.DateTime,System.String)~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1055:Uri return values should not be strings", Scope = "member", Target = "~M:Amazon.CloudFront.AmazonCloudFrontUrlSigner.GetCustomSignedURL(Amazon.CloudFront.AmazonCloudFrontUrlSigner.Protocol,System.String,System.IO.TextReader,System.String,System.String,System.DateTime,System.DateTime,System.String)~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1055:Uri return values should not be strings", Scope = "member", Target = "~M:Amazon.CloudFront.AmazonCloudFrontUrlSigner.GetCustomSignedURL(Amazon.CloudFront.AmazonCloudFrontUrlSigner.Protocol,System.String,System.IO.TextReader,System.String,System.String,System.DateTime,System.String)~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1055:Uri return values should not be strings", Scope = "member", Target = "~M:Amazon.CloudFront.AmazonCloudFrontUrlSigner.GetCustomSignedURL(System.String,System.IO.TextReader,System.String,System.DateTime,System.DateTime,System.String)~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1055:Uri return values should not be strings", Scope = "member", Target = "~M:Amazon.CloudFront.AmazonCloudFrontUrlSigner.GetCustomSignedURL(System.String,System.IO.TextReader,System.String,System.DateTime,System.String)~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1055:Uri return values should not be strings", Scope = "member", Target = "~M:Amazon.CloudFront.AmazonCloudFrontUrlSigner.SignUrl(System.String,System.String,System.IO.TextReader,System.String)~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1055:Uri return values should not be strings", Scope = "member", Target = "~M:Amazon.CloudFront.AmazonCloudFrontUrlSigner.SignUrlCanned(System.String,System.String,System.IO.TextReader,System.DateTime)~System.String")]

