/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License").
 * You may not use this file except in compliance with the License.
 * A copy of the License is located at
 *
 *  http://aws.amazon.com/apache2.0
 *
 * or in the "license" file accompanying this file. This file is distributed
 * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Design", "CA1033:Interface methods should be callable by child types", Justification = "<Pending>", Scope = "member", Target = "~M:Amazon.SSOOIDC.AmazonSSOOIDCClient.Amazon#Runtime#SharedInterfaces#ICoreAmazonSSOOIDC#GetSsoToken(Amazon.Runtime.SharedInterfaces.GetSsoTokenRequest)~Amazon.Runtime.SharedInterfaces.GetSsoTokenResponse")]
[assembly: SuppressMessage("Design", "CA1033:Interface methods should be callable by child types", Justification = "<Pending>", Scope = "member", Target = "~M:Amazon.SSOOIDC.AmazonSSOOIDCClient.Amazon#Runtime#SharedInterfaces#ICoreAmazonSSOOIDC#GetSsoTokenAsync(Amazon.Runtime.SharedInterfaces.GetSsoTokenRequest)~System.Threading.Tasks.Task{Amazon.Runtime.SharedInterfaces.GetSsoTokenResponse}")]
[assembly: SuppressMessage("Design", "CA1033:Interface methods should be callable by child types", Justification = "<Pending>", Scope = "member", Target = "~M:Amazon.SSOOIDC.AmazonSSOOIDCClient.Amazon#Runtime#SharedInterfaces#ICoreAmazonSSOOIDC_V2#GetSsoTokenAsync(Amazon.Runtime.SharedInterfaces.GetSsoTokenRequest,System.Threading.CancellationToken)~System.Threading.Tasks.Task{Amazon.Runtime.SharedInterfaces.GetSsoTokenResponse}")]
[assembly: SuppressMessage("Design", "CA1033:Interface methods should be callable by child types", Justification = "<Pending>", Scope = "member", Target = "~M:Amazon.SSOOIDC.AmazonSSOOIDCClient.Amazon#Runtime#SharedInterfaces#ICoreAmazonSSOOIDC#RefreshToken(Amazon.Runtime.SharedInterfaces.GetSsoTokenResponse)~Amazon.Runtime.SharedInterfaces.GetSsoTokenResponse")]
[assembly: SuppressMessage("Design", "CA1033:Interface methods should be callable by child types", Justification = "<Pending>", Scope = "member", Target = "~M:Amazon.SSOOIDC.AmazonSSOOIDCClient.Amazon#Runtime#SharedInterfaces#ICoreAmazonSSOOIDC#RefreshTokenAsync(Amazon.Runtime.SharedInterfaces.GetSsoTokenResponse)~System.Threading.Tasks.Task{Amazon.Runtime.SharedInterfaces.GetSsoTokenResponse}")]
[assembly: SuppressMessage("AwsSdkRules", "CR1003:Do not use DateTime.Now or DateTime.UtcNow, use AWSSDKUtils.CorrectedNow or AWSSDKUtils.CorrectedUtcNow", Justification = "<Pending>", Scope = "member", Target = "~M:Amazon.SSOOIDC.Internal.CoreAmazonSSOOIDC.GetSsoToken(Amazon.SSOOIDC.IAmazonSSOOIDC,Amazon.Runtime.SharedInterfaces.GetSsoTokenRequest,Amazon.SSOOIDC.Internal.IGetSsoTokenContext)~Amazon.Runtime.SharedInterfaces.GetSsoTokenResponse")]
[assembly: SuppressMessage("AwsSdkRules", "CR1003:Do not use DateTime.Now or DateTime.UtcNow, use AWSSDKUtils.CorrectedNow or AWSSDKUtils.CorrectedUtcNow", Justification = "<Pending>", Scope = "member", Target = "~M:Amazon.SSOOIDC.Internal.CoreAmazonSSOOIDC.GetSsoTokenAsync(Amazon.SSOOIDC.IAmazonSSOOIDC,Amazon.Runtime.SharedInterfaces.GetSsoTokenRequest,Amazon.SSOOIDC.Internal.IGetSsoTokenContext)~System.Threading.Tasks.Task{Amazon.Runtime.SharedInterfaces.GetSsoTokenResponse}")]
[assembly: SuppressMessage("AwsSdkRules", "CR1003:Do not use DateTime.Now or DateTime.UtcNow, use AWSSDKUtils.CorrectedNow or AWSSDKUtils.CorrectedUtcNow", Justification = "<Pending>", Scope = "member", Target = "~M:Amazon.SSOOIDC.Internal.CoreAmazonSSOOIDC.GetSsoTokenAsync(Amazon.SSOOIDC.IAmazonSSOOIDC,Amazon.Runtime.SharedInterfaces.GetSsoTokenRequest,Amazon.SSOOIDC.Internal.IGetSsoTokenContext,System.Threading.CancellationToken)~System.Threading.Tasks.Task{Amazon.Runtime.SharedInterfaces.GetSsoTokenResponse}")]
[assembly: SuppressMessage("AwsSdkRules", "CR1003:Do not use DateTime.Now or DateTime.UtcNow, use AWSSDKUtils.CorrectedNow or AWSSDKUtils.CorrectedUtcNow", Justification = "<Pending>", Scope = "member", Target = "~M:Amazon.SSOOIDC.Internal.CoreAmazonSSOOIDC.PollForSsoToken(Amazon.SSOOIDC.IAmazonSSOOIDC,Amazon.SSOOIDC.Model.CreateTokenRequest,System.Int32,System.DateTime,Amazon.SSOOIDC.Internal.IGetSsoTokenContext)~Amazon.SSOOIDC.Model.CreateTokenResponse")]
[assembly: SuppressMessage("AwsSdkRules", "CR1003:Do not use DateTime.Now or DateTime.UtcNow, use AWSSDKUtils.CorrectedNow or AWSSDKUtils.CorrectedUtcNow", Justification = "<Pending>", Scope = "member", Target = "~M:Amazon.SSOOIDC.Internal.CoreAmazonSSOOIDC.PollForSsoTokenAsync(Amazon.SSOOIDC.IAmazonSSOOIDC,Amazon.SSOOIDC.Model.CreateTokenRequest,System.Int32,System.DateTime,Amazon.SSOOIDC.Internal.IGetSsoTokenContext,System.Threading.CancellationToken)~System.Threading.Tasks.Task{Amazon.SSOOIDC.Model.CreateTokenResponse}")]
[assembly: SuppressMessage("AwsSdkRules", "CR1003:Do not use DateTime.Now or DateTime.UtcNow, use AWSSDKUtils.CorrectedNow or AWSSDKUtils.CorrectedUtcNow", Justification = "<Pending>", Scope = "member", Target = "~M:Amazon.SSOOIDC.Internal.CoreAmazonSSOOIDC.RefreshToken(Amazon.SSOOIDC.IAmazonSSOOIDC,Amazon.Runtime.SharedInterfaces.GetSsoTokenResponse)~Amazon.Runtime.SharedInterfaces.GetSsoTokenResponse")]
[assembly: SuppressMessage("AwsSdkRules", "CR1003:Do not use DateTime.Now or DateTime.UtcNow, use AWSSDKUtils.CorrectedNow or AWSSDKUtils.CorrectedUtcNow", Justification = "<Pending>", Scope = "member", Target = "~M:Amazon.SSOOIDC.Internal.CoreAmazonSSOOIDC.RefreshTokenAsync(Amazon.SSOOIDC.IAmazonSSOOIDC,Amazon.Runtime.SharedInterfaces.GetSsoTokenResponse)~System.Threading.Tasks.Task{Amazon.Runtime.SharedInterfaces.GetSsoTokenResponse}")]
