// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ServiceClientGenerator.Generators.Marshallers
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class JsonRPCStructureMarshaller : BaseRequestMarshaller
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 6 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"

	AddLicenseHeader();

	AddCommonUsingStatements();

            
            #line default
            #line hidden
            this.Write("#pragma warning disable CS0612,CS0618\r\nnamespace ");
            
            #line 12 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Config.Namespace));
            
            #line default
            #line hidden
            this.Write(".Model.Internal.MarshallTransformations\r\n{\r\n\t/// <summary>\r\n\t/// ");
            
            #line 15 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Structure.Name));
            
            #line default
            #line hidden
            this.Write(" Marshaller\r\n\t/// </summary>\r\n\tpublic class ");
            
            #line 17 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Structure.Name));
            
            #line default
            #line hidden
            this.Write("Marshaller : IRequestMarshaller<");
            
            #line 17 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Structure.Name));
            
            #line default
            #line hidden
            this.Write(@", JsonMarshallerContext> 
	{
        /// <summary>
        /// Unmarshaller the response from the service to the response class.
        /// </summary>  
        /// <param name=""requestObject""></param>
        /// <param name=""context""></param>
        /// <returns></returns>
		public void Marshall(");
            
            #line 25 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Structure.Name));
            
            #line default
            #line hidden
            this.Write(" requestObject, JsonMarshallerContext context)\r\n\t\t{\r\n\t\t\tif(requestObject == null)" +
                    "\r\n\t\t\t\treturn;\r\n");
            
            #line 29 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"

    ProcessMembers(0, "requestObject", this.Structure.Members);

            
            #line default
            #line hidden
            this.Write("\t\t}\r\n\r\n        /// <summary>\r\n        /// Singleton Marshaller.\r\n        /// </su" +
                    "mmary>\r\n\t\tpublic readonly static ");
            
            #line 37 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Structure.Name));
            
            #line default
            #line hidden
            this.Write("Marshaller Instance = new ");
            
            #line 37 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Structure.Name));
            
            #line default
            #line hidden
            this.Write("Marshaller();\r\n\r\n\t}\r\n}\r\n\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 42 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"

	protected void ProcessMembers(int level, string variableName, IEnumerable<Member> members)
	{
		foreach(var member in members)
		{

        
        #line default
        #line hidden
        
        #line 48 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(new string(' ', level * 4)));

        
        #line default
        #line hidden
        
        #line 48 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("            if(");

        
        #line default
        #line hidden
        
        #line 48 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(variableName));

        
        #line default
        #line hidden
        
        #line 48 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(".IsSet");

        
        #line default
        #line hidden
        
        #line 48 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(member.PropertyName));

        
        #line default
        #line hidden
        
        #line 48 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("())\r\n");

        
        #line default
        #line hidden
        
        #line 49 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(new string(' ', level * 4)));

        
        #line default
        #line hidden
        
        #line 49 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("            {\r\n");

        
        #line default
        #line hidden
        
        #line 50 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(new string(' ', level * 4)));

        
        #line default
        #line hidden
        
        #line 50 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("                context.Writer.WritePropertyName(\"");

        
        #line default
        #line hidden
        
        #line 50 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(member.MarshallName));

        
        #line default
        #line hidden
        
        #line 50 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("\");\r\n");

        
        #line default
        #line hidden
        
        #line 51 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"

			string memberProperty = variableName + "." + member.PropertyName;
			// Only append .Value for nullable types that aren't already complex types
			if (member.IsNullable && !member.IsStructure && !member.IsList && !member.IsMap) 
			{
				memberProperty += ".Value";
			}
			if(member.IsStructure || member.IsList || member.IsMap)
			{
				this.ProcessStructure(level + 1, variableName + "." + member.PropertyName, member.Shape);
			}
            else if(!string.IsNullOrEmpty(member.CustomMarshallerTransformation))
            {
				DetermineCustomMarshallerJsonWriteMethod(member, memberProperty, level);

        
        #line default
        #line hidden
        
        #line 66 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"

            }
			else if(member.IsMemoryStream)
			{

        
        #line default
        #line hidden
        
        #line 71 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(new string(' ', level * 4)));

        
        #line default
        #line hidden
        
        #line 71 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("                context.Writer.WriteStringValue(StringUtils.FromMemoryStream(");

        
        #line default
        #line hidden
        
        #line 71 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(variableName + "." + member.PropertyName));

        
        #line default
        #line hidden
        
        #line 71 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("));\r\n");

        
        #line default
        #line hidden
        
        #line 72 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"

			}
			else
			{
				// Only use timestamp format based marshalling if format is not Unix epoch, which is the default for json/rest-json
				if(member.IsTimeStamp && member.TimestampFormat != TimestampFormat.UnixTimestamp)
				{

        
        #line default
        #line hidden
        
        #line 80 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(new string(' ', level * 4)));

        
        #line default
        #line hidden
        
        #line 80 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("                context.Writer.WriteStringValue(");

        
        #line default
        #line hidden
        
        #line 80 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(member.PrimitiveMarshaller));

        
        #line default
        #line hidden
        
        #line 80 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("(");

        
        #line default
        #line hidden
        
        #line 80 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(variableName + "." + member.PropertyName));

        
        #line default
        #line hidden
        
        #line 80 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("));\r\n");

        
        #line default
        #line hidden
        
        #line 81 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"

				}
				else if(member.Shape.IsDouble)
				{

        
        #line default
        #line hidden
        
        #line 86 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(new string(' ', level * 4)));

        
        #line default
        #line hidden
        
        #line 86 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("\t\t\t\tif(StringUtils.IsSpecialDoubleValue(");

        
        #line default
        #line hidden
        
        #line 86 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(memberProperty));

        
        #line default
        #line hidden
        
        #line 86 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("))\r\n");

        
        #line default
        #line hidden
        
        #line 87 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(new string(' ', level * 4)));

        
        #line default
        #line hidden
        
        #line 87 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("\t\t\t\t{\r\n");

        
        #line default
        #line hidden
        
        #line 88 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(new string(' ', level * 4)));

        
        #line default
        #line hidden
        
        #line 88 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("\t\t\t\t\tcontext.Writer.WriteStringValue(StringUtils.FromSpecialDoubleValue(");

        
        #line default
        #line hidden
        
        #line 88 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(memberProperty));

        
        #line default
        #line hidden
        
        #line 88 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("));\r\n");

        
        #line default
        #line hidden
        
        #line 89 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(new string(' ', level * 4)));

        
        #line default
        #line hidden
        
        #line 89 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("\t\t\t\t}\r\n");

        
        #line default
        #line hidden
        
        #line 90 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(new string(' ', level * 4)));

        
        #line default
        #line hidden
        
        #line 90 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("\t\t\t\telse\r\n");

        
        #line default
        #line hidden
        
        #line 91 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(new string(' ', level * 4)));

        
        #line default
        #line hidden
        
        #line 91 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("\t\t\t\t{\r\n");

        
        #line default
        #line hidden
        
        #line 92 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(new string(' ', level * 4)));

        
        #line default
        #line hidden
        
        #line 92 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("\t\t\t\t\tcontext.Writer.WriteNumberValue(");

        
        #line default
        #line hidden
        
        #line 92 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(memberProperty));

        
        #line default
        #line hidden
        
        #line 92 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(");\r\n");

        
        #line default
        #line hidden
        
        #line 93 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(new string(' ', level * 4)));

        
        #line default
        #line hidden
        
        #line 93 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("\t\t\t\t}\r\n");

        
        #line default
        #line hidden
        
        #line 94 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"

				}
				else if(member.Shape.IsFloat)
				{

        
        #line default
        #line hidden
        
        #line 99 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(new string(' ', level * 4)));

        
        #line default
        #line hidden
        
        #line 99 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("\t\t\t\tif(StringUtils.IsSpecialFloatValue(");

        
        #line default
        #line hidden
        
        #line 99 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(memberProperty));

        
        #line default
        #line hidden
        
        #line 99 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("))\r\n");

        
        #line default
        #line hidden
        
        #line 100 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(new string(' ', level * 4)));

        
        #line default
        #line hidden
        
        #line 100 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("\t\t\t\t{\r\n");

        
        #line default
        #line hidden
        
        #line 101 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(new string(' ', level * 4)));

        
        #line default
        #line hidden
        
        #line 101 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("\t\t\t\t\tcontext.Writer.WriteStringValue(StringUtils.FromSpecialFloatValue(");

        
        #line default
        #line hidden
        
        #line 101 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(memberProperty));

        
        #line default
        #line hidden
        
        #line 101 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("));\r\n");

        
        #line default
        #line hidden
        
        #line 102 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(new string(' ', level * 4)));

        
        #line default
        #line hidden
        
        #line 102 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("\t\t\t\t}\r\n");

        
        #line default
        #line hidden
        
        #line 103 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(new string(' ', level * 4)));

        
        #line default
        #line hidden
        
        #line 103 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("\t\t\t\telse\r\n");

        
        #line default
        #line hidden
        
        #line 104 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(new string(' ', level * 4)));

        
        #line default
        #line hidden
        
        #line 104 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("\t\t\t\t{\r\n");

        
        #line default
        #line hidden
        
        #line 105 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(new string(' ', level * 4)));

        
        #line default
        #line hidden
        
        #line 105 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("\t\t\t\t\tcontext.Writer.WriteNumberValue(");

        
        #line default
        #line hidden
        
        #line 105 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(memberProperty));

        
        #line default
        #line hidden
        
        #line 105 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(");\r\n");

        
        #line default
        #line hidden
        
        #line 106 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(new string(' ', level * 4)));

        
        #line default
        #line hidden
        
        #line 106 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("\t\t\t\t}\r\n");

        
        #line default
        #line hidden
        
        #line 107 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"

				}
				else
				{
					DetermineNormalJsonWriteMethod(member.Shape, memberProperty, level);

        
        #line default
        #line hidden
        
        #line 113 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"

				}
			}

        
        #line default
        #line hidden
        
        #line 117 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(new string(' ', level * 4)));

        
        #line default
        #line hidden
        
        #line 117 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("            }\r\n\r\n");

        
        #line default
        #line hidden
        
        #line 119 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"

			if(member.IsIdempotent)
			{

        
        #line default
        #line hidden
        
        #line 123 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(new string(' ', level * 4)));

        
        #line default
        #line hidden
        
        #line 123 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(" \t\t   else if(!(");

        
        #line default
        #line hidden
        
        #line 123 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(variableName));

        
        #line default
        #line hidden
        
        #line 123 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(".IsSet");

        
        #line default
        #line hidden
        
        #line 123 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(member.PropertyName));

        
        #line default
        #line hidden
        
        #line 123 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("()))\r\n");

        
        #line default
        #line hidden
        
        #line 124 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(new string(' ', level * 4)));

        
        #line default
        #line hidden
        
        #line 124 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(" \t\t   {\r\n");

        
        #line default
        #line hidden
        
        #line 125 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(new string(' ', level * 4)));

        
        #line default
        #line hidden
        
        #line 125 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("                context.Writer.WritePropertyName(\"");

        
        #line default
        #line hidden
        
        #line 125 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(member.MarshallName));

        
        #line default
        #line hidden
        
        #line 125 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("\");\r\n");

        
        #line default
        #line hidden
        
        #line 126 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(new string(' ', level * 4)));

        
        #line default
        #line hidden
        
        #line 126 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("                context.Writer.WriteStringValue(Guid.NewGuid().ToString());\r\n");

        
        #line default
        #line hidden
        
        #line 127 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(new string(' ', level * 4)));

        
        #line default
        #line hidden
        
        #line 127 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(" \t\t   }\r\n");

        
        #line default
        #line hidden
        
        #line 128 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
					
			}
		}
	}

    protected void ProcessRequestPayloadMember(int level, string variableName, Shape structure)
    {

        
        #line default
        #line hidden
        
        #line 135 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("\r\n");

        
        #line default
        #line hidden
        
        #line 137 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(new string(' ', level * 4)));

        
        #line default
        #line hidden
        
        #line 137 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("                var marshaller = ");

        
        #line default
        #line hidden
        
        #line 137 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(structure.Name));

        
        #line default
        #line hidden
        
        #line 137 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("Marshaller.Instance;\r\n");

        
        #line default
        #line hidden
        
        #line 138 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(new string(' ', level * 4)));

        
        #line default
        #line hidden
        
        #line 138 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("                marshaller.Marshall(");

        
        #line default
        #line hidden
        
        #line 138 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(variableName));

        
        #line default
        #line hidden
        
        #line 138 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(", context);\r\n");

        
        #line default
        #line hidden
        
        #line 139 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"

    }

	protected void ProcessStructure(int level, string variableName, Shape structure)
	{
			string flatVariableName = variableName.Replace(".", "");

			if(structure.IsList)
			{

        
        #line default
        #line hidden
        
        #line 149 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(new string(' ', level * 4)));

        
        #line default
        #line hidden
        
        #line 149 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("            context.Writer.WriteStartArray();\r\n");

        
        #line default
        #line hidden
        
        #line 150 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(new string(' ', level * 4)));

        
        #line default
        #line hidden
        
        #line 150 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("            foreach(var ");

        
        #line default
        #line hidden
        
        #line 150 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(flatVariableName));

        
        #line default
        #line hidden
        
        #line 150 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("ListValue in ");

        
        #line default
        #line hidden
        
        #line 150 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(variableName));

        
        #line default
        #line hidden
        
        #line 150 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(")\r\n");

        
        #line default
        #line hidden
        
        #line 151 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(new string(' ', level * 4)));

        
        #line default
        #line hidden
        
        #line 151 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("            {\r\n");

        
        #line default
        #line hidden
        
        #line 152 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
 
				ProcessStructure(level + 1, flatVariableName + "ListValue", structure.ListShape);

        
        #line default
        #line hidden
        
        #line 155 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(new string(' ', level * 4)));

        
        #line default
        #line hidden
        
        #line 155 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("            }\r\n");

        
        #line default
        #line hidden
        
        #line 156 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(new string(' ', level * 4)));

        
        #line default
        #line hidden
        
        #line 156 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("            context.Writer.WriteEndArray();\r\n");

        
        #line default
        #line hidden
        
        #line 157 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"

			}
			else if(structure.IsMap)
			{
				ProcessMap(level, variableName, structure);
			}
			else if(structure.IsDocument)
			{

        
        #line default
        #line hidden
        
        #line 166 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(new string(' ', level * 4)));

        
        #line default
        #line hidden
        
        #line 166 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("            Amazon.Runtime.Documents.Internal.Transform.DocumentMarshaller.Instan" +
        "ce.Write(context.Writer, ");

        
        #line default
        #line hidden
        
        #line 166 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(variableName));

        
        #line default
        #line hidden
        
        #line 166 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(");\r\n");

        
        #line default
        #line hidden
        
        #line 167 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"


			}
			else if(structure.IsStructure)
			{

        
        #line default
        #line hidden
        
        #line 173 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(new string(' ', level * 4)));

        
        #line default
        #line hidden
        
        #line 173 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("            context.Writer.WriteStartObject();\r\n\r\n");

        
        #line default
        #line hidden
        
        #line 175 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(new string(' ', level * 4)));

        
        #line default
        #line hidden
        
        #line 175 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("            var marshaller = ");

        
        #line default
        #line hidden
        
        #line 175 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(structure.Name));

        
        #line default
        #line hidden
        
        #line 175 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("Marshaller.Instance;\r\n");

        
        #line default
        #line hidden
        
        #line 176 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(new string(' ', level * 4)));

        
        #line default
        #line hidden
        
        #line 176 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("            marshaller.Marshall(");

        
        #line default
        #line hidden
        
        #line 176 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(variableName));

        
        #line default
        #line hidden
        
        #line 176 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(", context);\r\n\r\n");

        
        #line default
        #line hidden
        
        #line 178 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(new string(' ', level * 4)));

        
        #line default
        #line hidden
        
        #line 178 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("            context.Writer.WriteEndObject();\r\n");

        
        #line default
        #line hidden
        
        #line 179 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"

			}
			else if(structure.IsMemoryStream)
			{

        
        #line default
        #line hidden
        
        #line 184 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(new string(' ', level * 4)));

        
        #line default
        #line hidden
        
        #line 184 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("            context.Writer.WriteStringValue(StringUtils.FromMemoryStream(");

        
        #line default
        #line hidden
        
        #line 184 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(variableName));

        
        #line default
        #line hidden
        
        #line 184 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("));\r\n");

        
        #line default
        #line hidden
        
        #line 185 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"

			}
			else
			{
				// Only use timestamp format based marshalling if format is not Unix epoch, which is the default for json/rest-json
				if(structure.IsTimeStamp && structure.GetTimestampFormat(MarshallLocation.Body) != TimestampFormat.UnixTimestamp)
				{

        
        #line default
        #line hidden
        
        #line 193 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(new string(' ', level * 4)));

        
        #line default
        #line hidden
        
        #line 193 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("\t\t\t\tcontext.Writer.WriteStringValue(");

        
        #line default
        #line hidden
        
        #line 193 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(structure.PrimitiveMarshaller(MarshallLocation.Body)));

        
        #line default
        #line hidden
        
        #line 193 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("(");

        
        #line default
        #line hidden
        
        #line 193 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(variableName));

        
        #line default
        #line hidden
        
        #line 193 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("));\r\n");

        
        #line default
        #line hidden
        
        #line 194 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"

				}
				else
				{
					DetermineNormalJsonWriteMethod(structure, variableName, level);
				}
				
			}
	}

	protected void ProcessMap(int level, string variableName, Shape structure)
	{
		string flatVariableName = variableName.Replace(".", "");

        
        #line default
        #line hidden
        
        #line 208 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(new string(' ', level * 4)));

        
        #line default
        #line hidden
        
        #line 208 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("            context.Writer.WriteStartObject();\r\n");

        
        #line default
        #line hidden
        
        #line 209 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(new string(' ', level * 4)));

        
        #line default
        #line hidden
        
        #line 209 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("            foreach (var ");

        
        #line default
        #line hidden
        
        #line 209 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(flatVariableName));

        
        #line default
        #line hidden
        
        #line 209 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("Kvp in ");

        
        #line default
        #line hidden
        
        #line 209 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(variableName));

        
        #line default
        #line hidden
        
        #line 209 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(")\r\n");

        
        #line default
        #line hidden
        
        #line 210 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(new string(' ', level * 4)));

        
        #line default
        #line hidden
        
        #line 210 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("            {\r\n");

        
        #line default
        #line hidden
        
        #line 211 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(new string(' ', level * 4)));

        
        #line default
        #line hidden
        
        #line 211 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("                context.Writer.WritePropertyName(");

        
        #line default
        #line hidden
        
        #line 211 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(flatVariableName));

        
        #line default
        #line hidden
        
        #line 211 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("Kvp.Key);\r\n");

        
        #line default
        #line hidden
        
        #line 212 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(new string(' ', level * 4)));

        
        #line default
        #line hidden
        
        #line 212 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("                var ");

        
        #line default
        #line hidden
        
        #line 212 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(flatVariableName));

        
        #line default
        #line hidden
        
        #line 212 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("Value = ");

        
        #line default
        #line hidden
        
        #line 212 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(flatVariableName));

        
        #line default
        #line hidden
        
        #line 212 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("Kvp.Value;\r\n\r\n");

        
        #line default
        #line hidden
        
        #line 214 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
             // Check for null values - only null checks for sparse maps as defined in customizations

                bool isNullableMap = false;
                if (this.Structure != null)
                {
                    var memberWithMap = this.Structure.Members.FirstOrDefault(m => m.PropertyName == variableName.Split('.').Last());
                    isNullableMap = (memberWithMap != null && memberWithMap.UseNullable);
                }
                
                if (isNullableMap)
                {

        
        #line default
        #line hidden
        
        #line 226 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(new string(' ', level * 4)));

        
        #line default
        #line hidden
        
        #line 226 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("                if (");

        
        #line default
        #line hidden
        
        #line 226 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(flatVariableName));

        
        #line default
        #line hidden
        
        #line 226 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("Value == null)\r\n");

        
        #line default
        #line hidden
        
        #line 227 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(new string(' ', level * 4)));

        
        #line default
        #line hidden
        
        #line 227 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("                {\r\n");

        
        #line default
        #line hidden
        
        #line 228 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(new string(' ', level * 4)));

        
        #line default
        #line hidden
        
        #line 228 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("                    context.Writer.WriteNullValue();\r\n");

        
        #line default
        #line hidden
        
        #line 229 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(new string(' ', level * 4)));

        
        #line default
        #line hidden
        
        #line 229 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("                }\r\n");

        
        #line default
        #line hidden
        
        #line 230 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(new string(' ', level * 4)));

        
        #line default
        #line hidden
        
        #line 230 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("                else\r\n");

        
        #line default
        #line hidden
        
        #line 231 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(new string(' ', level * 4)));

        
        #line default
        #line hidden
        
        #line 231 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("                {\r\n");

        
        #line default
        #line hidden
        
        #line 232 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"

                }

                if(structure.ValueShape.IsBoolean)
                {
                    if(isNullableMap)
                    {

        
        #line default
        #line hidden
        
        #line 240 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(new string(' ', level * 4)));

        
        #line default
        #line hidden
        
        #line 240 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("                    context.Writer.WriteBooleanValue(");

        
        #line default
        #line hidden
        
        #line 240 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(flatVariableName));

        
        #line default
        #line hidden
        
        #line 240 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("Value.Value);\r\n");

        
        #line default
        #line hidden
        
        #line 241 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"

                    }
                    else
                    {

        
        #line default
        #line hidden
        
        #line 246 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(new string(' ', level * 4)));

        
        #line default
        #line hidden
        
        #line 246 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("                    context.Writer.WriteBooleanValue(");

        
        #line default
        #line hidden
        
        #line 246 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(flatVariableName));

        
        #line default
        #line hidden
        
        #line 246 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("Value);\r\n");

        
        #line default
        #line hidden
        
        #line 247 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"

                    }
                }
                else if(structure.ValueShape.IsInt || structure.ValueShape.IsLong || structure.ValueShape.IsFloat || structure.ValueShape.IsDouble)
                {
                    if(isNullableMap)
                    {

        
        #line default
        #line hidden
        
        #line 255 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(new string(' ', level * 4)));

        
        #line default
        #line hidden
        
        #line 255 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("                    context.Writer.WriteNumberValue(");

        
        #line default
        #line hidden
        
        #line 255 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(flatVariableName));

        
        #line default
        #line hidden
        
        #line 255 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("Value.Value);\r\n");

        
        #line default
        #line hidden
        
        #line 256 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"

                    }
                    else
                    {

        
        #line default
        #line hidden
        
        #line 261 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(new string(' ', level * 4)));

        
        #line default
        #line hidden
        
        #line 261 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("                    context.Writer.WriteNumberValue(");

        
        #line default
        #line hidden
        
        #line 261 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(flatVariableName));

        
        #line default
        #line hidden
        
        #line 261 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("Value);\r\n");

        
        #line default
        #line hidden
        
        #line 262 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"

                    }
                }
                else if(structure.ValueShape.IsTimeStamp)
                {
                    if(isNullableMap)
                    {
                        if (structure.ValueShape.data[Shape.TimestampFormatKey] != null && !string.Equals(structure.ValueShape.data["timestampFormat"].ToString(), "unixTimestamp"))
                        {

        
        #line default
        #line hidden
        
        #line 272 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(new string(' ', level * 4)));

        
        #line default
        #line hidden
        
        #line 272 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("                    context.Writer.WriteStringValue(");

        
        #line default
        #line hidden
        
        #line 272 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(flatVariableName));

        
        #line default
        #line hidden
        
        #line 272 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("Value.Value);\r\n");

        
        #line default
        #line hidden
        
        #line 273 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"

                        }
                        else
                        {

        
        #line default
        #line hidden
        
        #line 278 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(new string(' ', level * 4)));

        
        #line default
        #line hidden
        
        #line 278 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("                    context.Writer.WriteNumberValue(Convert.ToInt64(StringUtils.F" +
        "romDateTimeToUnixTimestamp(");

        
        #line default
        #line hidden
        
        #line 278 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(flatVariableName));

        
        #line default
        #line hidden
        
        #line 278 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("Value.Value)));\r\n");

        
        #line default
        #line hidden
        
        #line 279 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"

                        }
                    }
                    else
                    {
                        if (structure.ValueShape.data[Shape.TimestampFormatKey] != null && !string.Equals(structure.ValueShape.data["timestampFormat"].ToString(), "unixTimestamp"))
                        {

        
        #line default
        #line hidden
        
        #line 287 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(new string(' ', level * 4)));

        
        #line default
        #line hidden
        
        #line 287 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("                    context.Writer.WriteStringValue(");

        
        #line default
        #line hidden
        
        #line 287 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(flatVariableName));

        
        #line default
        #line hidden
        
        #line 287 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("Value);\r\n");

        
        #line default
        #line hidden
        
        #line 288 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"

                        }
                        else
                        {

        
        #line default
        #line hidden
        
        #line 293 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(new string(' ', level * 4)));

        
        #line default
        #line hidden
        
        #line 293 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("                    context.Writer.WriteNumberValue(Convert.ToInt64(StringUtils.F" +
        "romDateTimeToUnixTimestamp(");

        
        #line default
        #line hidden
        
        #line 293 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(flatVariableName));

        
        #line default
        #line hidden
        
        #line 293 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("Value)));\r\n");

        
        #line default
        #line hidden
        
        #line 294 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"

                        }
                    }
                }
                else
                {
                    if(isNullableMap)
                    {
                            ProcessStructure(level + 2, flatVariableName + "Value", structure.ValueShape);
                    }
                    else
                    {
                            ProcessStructure(level + 1, flatVariableName + "Value", structure.ValueShape);
                    }
                }

                // Close the else block for nullable maps
                if (isNullableMap)
                {

        
        #line default
        #line hidden
        
        #line 314 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(new string(' ', level * 4)));

        
        #line default
        #line hidden
        
        #line 314 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("                }\r\n");

        
        #line default
        #line hidden
        
        #line 315 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"

                }

        
        #line default
        #line hidden
        
        #line 318 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(new string(' ', level * 4)));

        
        #line default
        #line hidden
        
        #line 318 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("            }\r\n");

        
        #line default
        #line hidden
        
        #line 319 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(new string(' ', level * 4)));

        
        #line default
        #line hidden
        
        #line 319 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("            context.Writer.WriteEndObject();\r\n");

        
        #line default
        #line hidden
        
        #line 320 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"

	}

	protected void DetermineCustomMarshallerJsonWriteMethod(Member member, string memberProperty, int level)
	{
		if (String.Equals(member.CustomMarshallerTransformation,"Amazon.Util.AWSSDKUtils.ConvertToUnixEpochMilliseconds", StringComparison.OrdinalIgnoreCase))
		{

        
        #line default
        #line hidden
        
        #line 328 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(new string(' ', level * 4)));

        
        #line default
        #line hidden
        
        #line 328 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("                context.Writer.WriteNumberValue(");

        
        #line default
        #line hidden
        
        #line 328 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(member.CustomMarshallerTransformation));

        
        #line default
        #line hidden
        
        #line 328 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("(");

        
        #line default
        #line hidden
        
        #line 328 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(memberProperty));

        
        #line default
        #line hidden
        
        #line 328 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("));\r\n");

        
        #line default
        #line hidden
        
        #line 329 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"

		}
		else
		{

        
        #line default
        #line hidden
        
        #line 334 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(new string(' ', level * 4)));

        
        #line default
        #line hidden
        
        #line 334 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("                context.Writer.WriteStringValue(");

        
        #line default
        #line hidden
        
        #line 334 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(member.CustomMarshallerTransformation));

        
        #line default
        #line hidden
        
        #line 334 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("(");

        
        #line default
        #line hidden
        
        #line 334 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(memberProperty));

        
        #line default
        #line hidden
        
        #line 334 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("));\r\n");

        
        #line default
        #line hidden
        
        #line 335 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"

		}	
	}

	/// https://smithy.io/2.0/aws/protocols/aws-restjson1-protocol.html#json-shape-serialization
	/// timestamps in json protocols use unixtimestamp if none is specified (by default)
	protected void DetermineNormalJsonWriteMethod(Shape shape, string memberProperty, int level)
	{
		// One of the overloads for WriteStringValue accepts a datetime, which by default always uses ISO 8601-1 format.
		// If the timestamp format is UnixTimestamp or there is none specified, we need to write raw value in epoch seconds,
		// which can only be done by using WriteNumberValue.
		if (shape.IsString || shape.IsEnum)
		{

        
        #line default
        #line hidden
        
        #line 349 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(new string(' ', level * 4)));

        
        #line default
        #line hidden
        
        #line 349 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("                context.Writer.WriteStringValue(");

        
        #line default
        #line hidden
        
        #line 349 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(memberProperty));

        
        #line default
        #line hidden
        
        #line 349 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(");\r\n");

        
        #line default
        #line hidden
        
        #line 350 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"

		}
		else if (shape.IsTimeStamp)
		{
			if (shape.data[Shape.TimestampFormatKey] != null && !string.Equals(shape.data["timestampFormat"].ToString(),"unixTimestamp"))
			{

        
        #line default
        #line hidden
        
        #line 357 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(new string(' ', level * 4)));

        
        #line default
        #line hidden
        
        #line 357 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("                context.Writer.WriteStringValue(");

        
        #line default
        #line hidden
        
        #line 357 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(memberProperty));

        
        #line default
        #line hidden
        
        #line 357 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(");\r\n");

        
        #line default
        #line hidden
        
        #line 358 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"

			}
			else
			{

        
        #line default
        #line hidden
        
        #line 363 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(new string(' ', level * 4)));

        
        #line default
        #line hidden
        
        #line 363 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("                context.Writer.WriteNumberValue(Convert.ToInt64(StringUtils.FromD" +
        "ateTimeToUnixTimestamp(");

        
        #line default
        #line hidden
        
        #line 363 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(memberProperty));

        
        #line default
        #line hidden
        
        #line 363 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(")));\r\n");

        
        #line default
        #line hidden
        
        #line 364 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"

			}
		}
		else if (shape.IsInt || shape.IsLong || shape.IsFloat || shape.IsDouble)
		{
			// Simple numeric value

        
        #line default
        #line hidden
        
        #line 371 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(new string(' ', level * 4)));

        
        #line default
        #line hidden
        
        #line 371 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("                context.Writer.WriteNumberValue(");

        
        #line default
        #line hidden
        
        #line 371 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(memberProperty));

        
        #line default
        #line hidden
        
        #line 371 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(");\r\n");

        
        #line default
        #line hidden
        
        #line 372 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"

		}
		else if (shape.IsBoolean)
		{

        
        #line default
        #line hidden
        
        #line 377 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(new string(' ', level * 4)));

        
        #line default
        #line hidden
        
        #line 377 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write("                context.Writer.WriteBooleanValue(");

        
        #line default
        #line hidden
        
        #line 377 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(memberProperty));

        
        #line default
        #line hidden
        
        #line 377 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"
this.Write(");\r\n");

        
        #line default
        #line hidden
        
        #line 378 "C:\dev\Repos\aws-sdk-net\generator\ServiceClientGeneratorLib\Generators\Marshallers\JsonRPCStructureMarshaller.tt"

		}
		else
		{
			throw new Exception ("Unknown primitive type encountered");
		}
	}

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
}
