// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ServiceClientGenerator.Generators.SourceFiles
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class StructureGenerator : BaseGenerator
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 6 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"

    AddLicenseHeader();

            
            #line default
            #line hidden
            this.Write("using System;\r\nusing System.Collections.Generic;\r\nusing System.Xml.Serialization;" +
                    "\r\nusing System.Text;\r\nusing System.IO;\r\nusing System.Net;\r\n\r\nusing Amazon.Runtim" +
                    "e;\r\nusing Amazon.Runtime.Internal;\r\n");
            
            #line 18 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"

if(this.StructureType == StructureType.Request && this.Operation.AuthType.HasValue)
{

            
            #line default
            #line hidden
            this.Write("using Amazon.Runtime.Internal.Auth;\r\n");
            
            #line 23 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"

}

            
            #line default
            #line hidden
            
            #line 26 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"

if(this.Structure != null && (this.Structure.IsEvent || this.Structure.IsEventStream))
{

            
            #line default
            #line hidden
            this.Write("using Amazon.Runtime.EventStreams;\r\nusing Amazon.Runtime.EventStreams.Internal;\r\n" +
                    "");
            
            #line 32 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"

}

            
            #line default
            #line hidden
            this.Write("\r\nnamespace ");
            
            #line 36 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Config.Namespace));
            
            #line default
            #line hidden
            this.Write(".Model\r\n{\r\n");
            
            #line 38 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"
  
    if(this.StructureType == StructureType.Request)
        this.FormatOperationRequestDocumentation(this.Operation);
    else if (this.Operation != null && GeneratorHelpers.HasSuppressedResult(this.Operation))
        this.FormatVoidResultDocumentation(this.Operation.Name);
    else if(this.StructureType == StructureType.Response && (this.Structure == null || string.IsNullOrEmpty(this.Structure.Documentation)))
    {

            
            #line default
            #line hidden
            this.Write("    /// <summary>\r\n    /// This is the response object from the ");
            
            #line 47 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Operation.Name));
            
            #line default
            #line hidden
            this.Write(" operation.\r\n    /// </summary>\r\n");
            
            #line 49 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"

    }
    else
        this.FormatClassDocumentation(this.Structure);  

            
            #line default
            #line hidden
            
            #line 54 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"
      
    if(this.Structure != null && this.Structure.IsDeprecated)
        {

            
            #line default
            #line hidden
            this.Write("    [Obsolete(\"");
            
            #line 58 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Structure.DeprecationMessage));
            
            #line default
            #line hidden
            this.Write("\")]\r\n");
            
            #line 59 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"

        }
    if(this.Structure is ExceptionShape)
        {

            
            #line default
            #line hidden
            this.Write("    #if !NETSTANDARD\r\n    [Serializable]\r\n    #endif\r\n");
            
            #line 67 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"

        }

            
            #line default
            #line hidden
            
            #line 70 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"


    if(this.Structure != null && this.Structure.IsEventStream)
    { // top if block

            
            #line default
            #line hidden
            this.Write("\r\n    [System.Diagnostics.CodeAnalysis.SuppressMessage(\"Naming\", \"CA1710:Identifi" +
                    "ers should have correct suffix\", Justification = \"<Pending>\")]\r\n    public seale" +
                    "d class ");
            
            #line 77 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Structure.Name));
            
            #line default
            #line hidden
            this.Write(" : EnumerableEventStream<IEventStreamEvent, ");
            
            #line 77 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Config.ClassName));
            
            #line default
            #line hidden
            this.Write(@"EventStreamException>
    {
        ///summary>
        ///The mapping of event message to a generator function to construct the matching EventStream event
        ///</summary>
        protected override IDictionary<string,Func<IEventStreamMessage, IEventStreamEvent>> EventMapping {get;} =
        new Dictionary<string,Func<IEventStreamMessage,IEventStreamEvent>>
        {
");
            
            #line 85 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"

        foreach(var member in this.Structure.Members)
        {

            
            #line default
            #line hidden
            this.Write("            {\"");
            
            #line 89 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.PropertyName));
            
            #line default
            #line hidden
            this.Write("\", payload => new ");
            
            #line 89 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.DetermineType()));
            
            #line default
            #line hidden
            this.Write("(payload)},\r\n");
            
            #line 90 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"

        }

            
            #line default
            #line hidden
            this.Write("        };\r\n        /// <summary>\r\n        /// The mapping of event message to a " +
                    "generator function to construct the matching EventStream Exception\r\n        /// " +
                    "</summary>\r\n        protected override IDictionary<string,Func<IEventStreamMessa" +
                    "ge,");
            
            #line 97 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Config.ClassName));
            
            #line default
            #line hidden
            this.Write("EventStreamException>> ExceptionMapping {get;} =\r\n        new Dictionary<string,F" +
                    "unc<IEventStreamMessage,");
            
            #line 98 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Config.ClassName));
            
            #line default
            #line hidden
            this.Write(@"EventStreamException>>
        {
        };
        // Backing by a volatile bool. The flag only changes one way, so no need for a lock.
        // This is located in the subclass to be CLS compliant.
        private volatile bool _isProcessing;

        /// <summary>
        /// Whether the backround processing loop is running.
        /// </summary>
        protected override bool IsProcessing
        {
            get { return _isProcessing; }
            set { _isProcessing = value; }
        }
        public override event EventHandler<EventStreamEventReceivedArgs<IEventStreamEvent>> EventReceived;
        public override event EventHandler<EventStreamExceptionReceivedArgs<");
            
            #line 114 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Config.ClassName));
            
            #line default
            #line hidden
            this.Write("EventStreamException>> ExceptionReceived;\r\n        /// <summary>\r\n        /// Rai" +
                    "sed when an InvokeComplete event is received\r\n        /// </summary>\r\n");
            
            #line 118 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"

        foreach(var member in this.Structure.Members)
        {

            
            #line default
            #line hidden
            this.Write("        ///<summary>\r\n        ///Raised when an ");
            
            #line 123 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.PropertyName));
            
            #line default
            #line hidden
            this.Write(" event is received\r\n        public event EventHandler<EventStreamEventReceivedArg" +
                    "s<");
            
            #line 124 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.DetermineType()));
            
            #line default
            #line hidden
            this.Write(">> ");
            
            #line 124 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.PropertyName));
            
            #line default
            #line hidden
            this.Write("Received;\r\n");
            
            #line 125 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"

        }

            
            #line default
            #line hidden
            this.Write("        public ");
            
            #line 128 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Structure.Name));
            
            #line default
            #line hidden
            this.Write("(Stream stream) : this (stream, null)\r\n        {\r\n        }\r\n        public ");
            
            #line 131 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Structure.Name));
            
            #line default
            #line hidden
            this.Write(@"(Stream stream, IEventStreamDecoder eventStreamDecoder) : base(stream, eventStreamDecoder)
        {
            base.EventReceived += (sender,args) => EventReceived?.Invoke(this, args);
            base.ExceptionReceived += (sender,args) => ExceptionReceived?.Invoke(this, args);

            //Mapping the generic Event to more specific Events
            Decoder.MessageReceived += (sender, args) =>
            {
                IEventStreamEvent ev;
                try
                {
                    ev = ConvertMessageToEvent(args.Message);
                }
                catch(UnknownEventStreamException)
                {
                    throw new UnknownEventStreamException(""Received an unknown event stream type"");
                }
                EventReceived?.Invoke(this, new EventStreamEventReceivedArgs<IEventStreamEvent>(ev));

                //Call RaiseEvent until it returns true or all calls complete. This way only a subset of casts is perfromed
                // and we can avoid a cascade of nested if else statements. The result is thrown away
                var _ =
");
            
            #line 153 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"

                for(int i = 0; i < this.Structure.Members.Count() - 1; i++)
                {

            
            #line default
            #line hidden
            this.Write("                    RaiseEvent(");
            
            #line 157 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Structure.Members[i].PropertyName));
            
            #line default
            #line hidden
            this.Write("Received,ev) ||\r\n");
            
            #line 158 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"

                }

            
            #line default
            #line hidden
            this.Write("                    RaiseEvent(");
            
            #line 161 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Structure.Members.Last()));
            
            #line default
            #line hidden
            this.Write(@"Received,ev);
            };       
        }
        private bool RaiseEvent<T>(EventHandler<EventStreamEventReceivedArgs<T>> eventHandler, IEventStreamEvent ev) where T : class, IEventStreamEvent
        {
            var convertedEvent = ev as T;
            if (convertedEvent != null)
            {
                eventHandler?.Invoke(this, new EventStreamEventReceivedArgs<T>(convertedEvent));
                return true;
            }

            return false;
        }
");
            
            #line 175 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"

    }

            
            #line default
            #line hidden
            
            #line 178 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"

    bool hasStreamingMember = this.Structure?.Members.Any(member => member.IsStreaming) ?? false;
        
    bool structureContainsEventPayload = this.Structure?.Members.Any(member => member.IsEventPayload) ?? false;
    Member payloadMember = null;
    if(structureContainsEventPayload)
    {
        payloadMember = this.Structure?.Members.Single(member => member.IsEventPayload);
    }
    bool structureIsNotEventStream = this.Structure != null && !this.Structure.IsEventStream;
    bool structureIsEvent = this.Structure != null && this.Structure.IsEvent;
    if (structureIsNotEventStream && this.StructureType == StructureType.Response && hasStreamingMember) 
        {

            
            #line default
            #line hidden
            this.Write("    public partial class ");
            
            #line 192 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ClassName));
            
            #line default
            #line hidden
            
            #line 192 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.BaseClassString));
            
            #line default
            #line hidden
            this.Write(", IDisposable\r\n    {\r\n");
            
            #line 194 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"

        }
    else 
    {

            
            #line default
            #line hidden
            
            #line 199 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"

        if( (this.Structure == null) || (structureIsNotEventStream))
        {

            
            #line default
            #line hidden
            this.Write("    public partial class ");
            
            #line 203 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ClassName));
            
            #line default
            #line hidden
            
            #line 203 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.BaseClassString));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 204 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"

            if(structureIsEvent)
            {

            
            #line default
            #line hidden
            this.Write("        : IEventStreamEvent\r\n");
            
            #line 209 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"

            }

            
            #line default
            #line hidden
            
            #line 212 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"

            if(structureIsEvent && !structureContainsEventPayload)
            {

            
            #line default
            #line hidden
            this.Write("        ,IEventStreamTerminalEvent\r\n");
            
            #line 217 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"

            }

            
            #line default
            #line hidden
            this.Write("    {\r\n");
            
            #line 221 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"

        }

            
            #line default
            #line hidden
            
            #line 224 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"

    }

            
            #line default
            #line hidden
            
            #line 227 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"

    if(structureIsEvent)
    {

            
            #line default
            #line hidden
            this.Write("    public ");
            
            #line 231 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Structure.Name));
            
            #line default
            #line hidden
            this.Write("()\r\n    {\r\n    }\r\n\r\n    public ");
            
            #line 235 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Structure.Name));
            
            #line default
            #line hidden
            this.Write("(IEventStreamMessage message)\r\n    {\r\n");
            
            #line 237 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"

        if(structureContainsEventPayload)
        {

            
            #line default
            #line hidden
            this.Write("        ");
            
            #line 241 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(payloadMember.PropertyName));
            
            #line default
            #line hidden
            this.Write(" = new ");
            
            #line 241 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(payloadMember.DetermineType()));
            
            #line default
            #line hidden
            this.Write("(message.");
            
            #line 241 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(payloadMember.PropertyName));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 242 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"

        }

            
            #line default
            #line hidden
            this.Write("    }\r\n");
            
            #line 246 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"

    }

            
            #line default
            #line hidden
            
            #line 249 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"

        if(structureIsNotEventStream)
        {
            if(this.IsWrapped)
            {

            
            #line default
            #line hidden
            this.Write("        private ");
            
            #line 255 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Structure.Name));
            
            #line default
            #line hidden
            this.Write(" _response;\r\n\r\n        /// <summary>\r\n        /// Gets and sets the ");
            
            #line 258 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Structure.Name));
            
            #line default
            #line hidden
            this.Write(" property.\r\n        /// </summary>\r\n        public ");
            
            #line 260 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Structure.Name));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 260 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Structure.Name));
            
            #line default
            #line hidden
            this.Write("\r\n        {\r\n            get { return this._response; }\r\n            set { this._" +
                    "response = value; }\r\n        }\r\n");
            
            #line 265 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"

            }
            else
            {
                foreach(var member in this.Structure.Members)
                {
                    if (member.IsExcluded)
                        continue;

            
            #line default
            #line hidden
            this.Write("        private ");
            
            #line 274 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.DetermineType()));
            
            #line default
            #line hidden
            
            #line 274 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.IsNullable ? "?" : ""));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 274 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.VariableName));
            
            #line default
            #line hidden
            
            #line 274 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ShouldInstantiate ? string.Format(" = new {0}();", member.DetermineType()) : ";"));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 275 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"

                }

            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 279 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"

                AddSimpleRequestConstructors(this.ClassName, this.Structure, this.Config.Namespace);

                if(this.Structure is ExceptionShape)
                {
                    var exceptionShape = (ExceptionShape)this.Structure;
                    if (exceptionShape.IsRetryable)
                    {

            
            #line default
            #line hidden
            this.Write("        private RetryableDetails _retryableDetails = new RetryableDetails(");
            
            #line 288 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(exceptionShape.Throttling.ToString().ToLower()));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 289 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"


            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 292 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"

                    }

            
            #line default
            #line hidden
            this.Write("        /// <summary>\r\n        /// Constructs a new ");
            
            #line 2 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\.\Exceptions\ExceptionConstructors.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Structure.Name));
            
            #line default
            #line hidden
            this.Write(" with the specified error\r\n        /// message.\r\n        /// </summary>\r\n        " +
                    "/// <param name=\"message\">\r\n        /// Describes the error encountered.\r\n      " +
                    "  /// </param>\r\n        public ");
            
            #line 8 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\.\Exceptions\ExceptionConstructors.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Structure.Name));
            
            #line default
            #line hidden
            this.Write("(string message) \r\n            : base(message) {}\r\n\r\n        /// <summary>\r\n     " +
                    "   /// Construct instance of ");
            
            #line 12 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\.\Exceptions\ExceptionConstructors.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Structure.Name));
            
            #line default
            #line hidden
            this.Write("\r\n        /// </summary>\r\n        /// <param name=\"message\"></param>\r\n        ///" +
                    " <param name=\"innerException\"></param>\r\n        public ");
            
            #line 16 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\.\Exceptions\ExceptionConstructors.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Structure.Name));
            
            #line default
            #line hidden
            this.Write("(string message, Exception innerException) \r\n            : base(message, innerExc" +
                    "eption) {}\r\n\r\n        /// <summary>\r\n        /// Construct instance of ");
            
            #line 20 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\.\Exceptions\ExceptionConstructors.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Structure.Name));
            
            #line default
            #line hidden
            this.Write("\r\n        /// </summary>\r\n        /// <param name=\"innerException\"></param>\r\n    " +
                    "    public ");
            
            #line 23 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\.\Exceptions\ExceptionConstructors.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Structure.Name));
            
            #line default
            #line hidden
            this.Write("(Exception innerException) \r\n            : base(innerException) {}\r\n\r\n        ///" +
                    " <summary>\r\n        /// Construct instance of ");
            
            #line 27 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\.\Exceptions\ExceptionConstructors.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Structure.Name));
            
            #line default
            #line hidden
            this.Write(@"
        /// </summary>
        /// <param name=""message""></param>
        /// <param name=""innerException""></param>
        /// <param name=""errorType""></param>
        /// <param name=""errorCode""></param>
        /// <param name=""requestId""></param>
        /// <param name=""statusCode""></param>
        public ");
            
            #line 35 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\.\Exceptions\ExceptionConstructors.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Structure.Name));
            
            #line default
            #line hidden
            this.Write(@"(string message, Exception innerException, ErrorType errorType, string errorCode, string requestId, HttpStatusCode statusCode) 
            : base(message, innerException, errorType, errorCode, requestId, statusCode) {}

        /// <summary>
        /// Construct instance of ");
            
            #line 39 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\.\Exceptions\ExceptionConstructors.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Structure.Name));
            
            #line default
            #line hidden
            this.Write(@"
        /// </summary>
        /// <param name=""message""></param>
        /// <param name=""errorType""></param>
        /// <param name=""errorCode""></param>
        /// <param name=""requestId""></param>
        /// <param name=""statusCode""></param>
        public ");
            
            #line 46 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\.\Exceptions\ExceptionConstructors.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Structure.Name));
            
            #line default
            #line hidden
            this.Write("(string message, ErrorType errorType, string errorCode, string requestId, HttpSta" +
                    "tusCode statusCode) \r\n            : base(message, errorType, errorCode, requestI" +
                    "d, statusCode) {}\r\n\r\n");
            this.Write("\r\n");
            this.Write("#if !NETSTANDARD\r\n        /// <summary>\r\n        /// Constructs a new instance of" +
                    " the ");
            
            #line 3 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\.\Exceptions\ExceptionSerialization.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Structure.Name));
            
            #line default
            #line hidden
            this.Write(@" class with serialized data.
        /// </summary>
        /// <param name=""info"">The <see cref=""T:System.Runtime.Serialization.SerializationInfo"" /> that holds the serialized object data about the exception being thrown.</param>
        /// <param name=""context"">The <see cref=""T:System.Runtime.Serialization.StreamingContext"" /> that contains contextual information about the source or destination.</param>
        /// <exception cref=""T:System.ArgumentNullException"">The <paramref name=""info"" /> parameter is null. </exception>
        /// <exception cref=""T:System.Runtime.Serialization.SerializationException"">The class name is null or <see cref=""P:System.Exception.HResult"" /> is zero (0). </exception>
        protected ");
            
            #line 9 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\.\Exceptions\ExceptionSerialization.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Structure.Name));
            
            #line default
            #line hidden
            this.Write("(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serializatio" +
                    "n.StreamingContext context)\r\n            : base(info, context)\r\n        {\r\n");
            
            #line 12 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\.\Exceptions\ExceptionSerialization.t4"
          
            foreach(var member in this.Structure.Members)
			{

            
            #line default
            #line hidden
            this.Write("            this.");
            
            #line 16 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\.\Exceptions\ExceptionSerialization.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.PropertyName));
            
            #line default
            #line hidden
            this.Write(" = (");
            
            #line 16 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\.\Exceptions\ExceptionSerialization.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.DetermineType()));
            
            #line default
            #line hidden
            this.Write(")info.GetValue(\"");
            
            #line 16 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\.\Exceptions\ExceptionSerialization.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.PropertyName));
            
            #line default
            #line hidden
            this.Write("\", typeof(");
            
            #line 16 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\.\Exceptions\ExceptionSerialization.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.DetermineType()));
            
            #line default
            #line hidden
            this.Write("));\r\n");
            
            #line 17 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\.\Exceptions\ExceptionSerialization.t4"

            }

            
            #line default
            #line hidden
            this.Write("        }\r\n\r\n        /// <summary>\r\n        /// Sets the <see cref=\"T:System.Runt" +
                    "ime.Serialization.SerializationInfo\" /> with information about the exception.\r\n " +
                    "       /// </summary>\r\n        /// <param name=\"info\">The <see cref=\"T:System.Ru" +
                    "ntime.Serialization.SerializationInfo\" /> that holds the serialized object data " +
                    "about the exception being thrown.</param>\r\n        /// <param name=\"context\">The" +
                    " <see cref=\"T:System.Runtime.Serialization.StreamingContext\" /> that contains co" +
                    "ntextual information about the source or destination.</param>\r\n        /// <exce" +
                    "ption cref=\"T:System.ArgumentNullException\">The <paramref name=\"info\" /> paramet" +
                    "er is a null reference (Nothing in Visual Basic). </exception>\r\n#if BCL35\r\n     " +
                    "   [System.Security.Permissions.SecurityPermission(\r\n            System.Security" +
                    ".Permissions.SecurityAction.LinkDemand,\r\n            Flags = System.Security.Per" +
                    "missions.SecurityPermissionFlag.SerializationFormatter)]\r\n#endif\r\n        [Syste" +
                    "m.Security.SecurityCritical]\r\n        // These FxCop rules are giving false-posi" +
                    "tives for this method\r\n        [System.Diagnostics.CodeAnalysis.SuppressMessage(" +
                    "\"Microsoft.Security\", \"CA2123:OverrideLinkDemandsShouldBeIdenticalToBase\")]\r\n   " +
                    "     [System.Diagnostics.CodeAnalysis.SuppressMessage(\"Microsoft.Security\", \"CA2" +
                    "134:MethodsMustOverrideWithConsistentTransparencyFxCopRule\")]\r\n        public ov" +
                    "erride void GetObjectData(System.Runtime.Serialization.SerializationInfo info, S" +
                    "ystem.Runtime.Serialization.StreamingContext context)\r\n        {\r\n            ba" +
                    "se.GetObjectData(info, context);\r\n");
            
            #line 40 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\.\Exceptions\ExceptionSerialization.t4"

            foreach(var member in this.Structure.Members)
			{

            
            #line default
            #line hidden
            this.Write("            info.AddValue(\"");
            
            #line 44 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\.\Exceptions\ExceptionSerialization.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.PropertyName));
            
            #line default
            #line hidden
            this.Write("\", this.");
            
            #line 44 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\.\Exceptions\ExceptionSerialization.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.PropertyName));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 45 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\.\Exceptions\ExceptionSerialization.t4"

            }

            
            #line default
            #line hidden
            this.Write("        }\r\n#endif\r\n");
            this.Write("\r\n");
            
            #line 297 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"

                }
                foreach(var member in this.Structure.Members)
                {
                    if (member.IsExcluded)
                        continue;

            
            #line default
            #line hidden
            
            #line 304 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"
 this.FormatPropertyDocumentation(member); 
            
            #line default
            #line hidden
            
            #line 305 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"
      
                    if(member.IsDeprecated)
                    {

            
            #line default
            #line hidden
            this.Write("        [Obsolete(\"");
            
            #line 309 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.DeprecationMessage));
            
            #line default
            #line hidden
            this.Write("\")]\r\n");
            
            #line 310 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"

                    }

                    var propertyAttributes = new List<string>();
                    if(member.IsRequired && !member.IsIdempotent)
                    {
                        propertyAttributes.Add("Required=true");
                    }
                    if (member.Shape.Sensitive)
                    {
                        propertyAttributes.Add("Sensitive=true");
                    }
                    if (member.Shape.Min.HasValue)
                    {
                        propertyAttributes.Add("Min=" + member.Shape.Min);
                    }
                    if (member.Shape.Max.HasValue)
                    {
                        propertyAttributes.Add("Max=" + member.Shape.Max);
                    }
                    if (propertyAttributes.Count > 0)
                    {

            
            #line default
            #line hidden
            this.Write("        [AWSProperty(");
            
            #line 333 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Join(", ", propertyAttributes)));
            
            #line default
            #line hidden
            this.Write(")]\r\n");
            
            #line 334 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"

                    }

            
            #line default
            #line hidden
            this.Write("        ");
            
            #line 337 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.AccessModifier));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 337 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.DetermineType()));
            
            #line default
            #line hidden
            
            #line 337 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.UseNullable ? "?" : ""));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 337 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.PropertyName));
            
            #line default
            #line hidden
            this.Write("\r\n        {\r\n");
            
            #line 339 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"

                    if(member.IsNullable && !member.UseNullable)
                    {

            
            #line default
            #line hidden
            this.Write("            get { return this.");
            
            #line 343 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.VariableName));
            
            #line default
            #line hidden
            this.Write(".GetValueOrDefault(); }\r\n");
            
            #line 344 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"

                    }
                    else
                    {

            
            #line default
            #line hidden
            this.Write("            get { return this.");
            
            #line 349 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.VariableName));
            
            #line default
            #line hidden
            this.Write("; }\r\n");
            
            #line 350 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"

                    }

            
            #line default
            #line hidden
            this.Write("            set { ");
            
            #line 353 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.IsBackwardsCompatibleDateTimeProperty ? "this." + member.BackwardCompatibilityVariableName + " = " : ""));
            
            #line default
            #line hidden
            this.Write("this.");
            
            #line 353 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.VariableName));
            
            #line default
            #line hidden
            this.Write(" = value; }\r\n        }\r\n\r\n");
            
            #line 356 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"

                    if (member.EmitIsSetProperties)
                    {

            
            #line default
            #line hidden
            this.Write("        /// <summary>\r\n        /// This property is set to true if the property <" +
                    "seealso cref=\"");
            
            #line 361 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.PropertyName));
            
            #line default
            #line hidden
            this.Write(@"""/>
        /// is set; false otherwise.
        /// This property can be used to determine if the related property
        /// was returned by a service response or if the related property
        /// should be sent to the service during a service call.
        /// </summary>
        /// <returns>
        /// True if the related property was set or will be sent to a service; false otherwise.
        /// </returns>
");
            
            #line 370 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"
      
                        if(member.IsDeprecated)
                        {

            
            #line default
            #line hidden
            this.Write("        [Obsolete(\"");
            
            #line 374 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.DeprecationMessage));
            
            #line default
            #line hidden
            this.Write("\")]\r\n");
            
            #line 375 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"

                        }

            
            #line default
            #line hidden
            this.Write("        public bool Is");
            
            #line 378 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.PropertyName));
            
            #line default
            #line hidden
            this.Write("Set\r\n        {\r\n            get\r\n            {\r\n                return Amazon.Uti" +
                    "l.Internal.InternalSDKUtils.GetIsSet(this.");
            
            #line 382 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.VariableName));
            
            #line default
            #line hidden
            this.Write(");\r\n            }\r\n            set\r\n            {\r\n                Amazon.Util.In" +
                    "ternal.InternalSDKUtils.SetIsSet(value, ref this.");
            
            #line 386 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.VariableName));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 387 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"

                        if(member.IsBackwardsCompatibleDateTimeProperty)
                        {

            
            #line default
            #line hidden
            this.Write("  \r\n                Amazon.Util.Internal.InternalSDKUtils.SetIsSet(value, ref thi" +
                    "s.");
            
            #line 391 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.BackwardCompatibilityVariableName));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 392 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"

                        }

            
            #line default
            #line hidden
            this.Write("            }\r\n        }\r\n\r\n");
            
            #line 398 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"

                    }

            
            #line default
            #line hidden
            this.Write("        // Check to see if ");
            
            #line 401 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.PropertyName));
            
            #line default
            #line hidden
            this.Write(" property is set\r\n        internal bool IsSet");
            
            #line 402 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.PropertyName));
            
            #line default
            #line hidden
            this.Write("()\r\n        {\r\n");
            
            #line 404 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"

                    if (member.EmitIsSetProperties)
                    {

            
            #line default
            #line hidden
            this.Write("            return this.Is");
            
            #line 408 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.PropertyName));
            
            #line default
            #line hidden
            this.Write("Set; \r\n");
            
            #line 409 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"

                    }
                    else if (member.IsNullable)
                    {

            
            #line default
            #line hidden
            this.Write("            return this.");
            
            #line 414 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.VariableName));
            
            #line default
            #line hidden
            this.Write(".HasValue; \r\n");
            
            #line 415 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"

                    }
                    else if (member.IsMap || member.IsList)
                    {

            
            #line default
            #line hidden
            this.Write("            return this.");
            
            #line 420 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.VariableName));
            
            #line default
            #line hidden
            this.Write(" != null && this.");
            
            #line 420 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.VariableName));
            
            #line default
            #line hidden
            this.Write(".Count > 0; \r\n");
            
            #line 421 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"

                    }
                    else if (member.IsDocument)
                    {

            
            #line default
            #line hidden
            this.Write("            return !this.");
            
            #line 426 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.VariableName));
            
            #line default
            #line hidden
            this.Write(".IsNull();\r\n");
            
            #line 427 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"

                    }
                    else
                    {

            
            #line default
            #line hidden
            this.Write("            return this.");
            
            #line 432 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.VariableName));
            
            #line default
            #line hidden
            this.Write(" != null;\r\n");
            
            #line 433 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"

                    }

            
            #line default
            #line hidden
            this.Write("        }\r\n\r\n");
            
            #line 438 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"

                }

                if (this.StructureType == StructureType.Request && this.Operation.AuthType.HasValue)
                {

            
            #line default
            #line hidden
            this.Write("        /// <summary>\r\n        /// Get the signer to use for this request.\r\n     " +
                    "   /// </summary>\r\n        /// <returns>A signer for this request.</returns>\r\n  " +
                    "      override protected AbstractAWSSigner CreateSigner()\r\n        {\r\n");
            
            #line 450 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"

                    switch (this.Operation.AuthType.Value)
                    {
                        case OperationAuthType.None:

            
            #line default
            #line hidden
            this.Write("            return new NullSigner();\r\n");
            
            #line 456 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"

                        break;
                        case OperationAuthType.V4:

            
            #line default
            #line hidden
            this.Write("            return new AWS4Signer();\r\n");
            
            #line 461 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"

                        break;
                        case OperationAuthType.V4UnsignedBody:

            
            #line default
            #line hidden
            this.Write("            return new AWS4Signer(false);\r\n");
            
            #line 466 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"

                        break;
                        case OperationAuthType.Bearer:

            
            #line default
            #line hidden
            this.Write("            return new BearerTokenSigner();\r\n");
            
            #line 471 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"

                        break;
                        default:
                            throw new ArgumentException("Unhandled value for operation authtype:" + this.Operation.AuthType.Value);
                    }

            
            #line default
            #line hidden
            this.Write("        }\r\n");
            
            #line 478 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"

                }
                // Flexible checksum overrides to allow response validation configuration on the request
                if (this.StructureType == StructureType.Request && !string.IsNullOrEmpty(this.Operation.ChecksumConfiguration?.RequestValidationModeMember))
                {

            
            #line default
            #line hidden
            this.Write(@"  
#region Flexible checksum properties
        /// <summary>
        /// This must be enabled to retrieve the checksum
        /// </summary>
        protected override CoreChecksumResponseBehavior CoreChecksumMode
        {
            get
            {
                if (IsSet");
            
            #line 492 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Operation.ChecksumConfiguration.RequestValidationModeMember));
            
            #line default
            #line hidden
            this.Write("())\r\n                {\r\n                    return (CoreChecksumResponseBehavior)" +
                    "Enum.Parse(typeof(CoreChecksumResponseBehavior), this.");
            
            #line 494 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Operation.ChecksumConfiguration.RequestValidationModeMember));
            
            #line default
            #line hidden
            this.Write(");\r\n                }\r\n\r\n                return CoreChecksumResponseBehavior.DISA" +
                    "BLED;\r\n            }\r\n        }\r\n\r\n        private static List<CoreChecksumAlgor" +
                    "ithm> _supportedChecksumAlgorithms = new List<CoreChecksumAlgorithm>\r\n        {\r" +
                    "\n            ");
            
            #line 503 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Join(", ", Operation.ChecksumConfiguration?.ResponseAlgorithms?.Select(s => $"CoreChecksumAlgorithm.{s}").ToArray())));
            
            #line default
            #line hidden
            this.Write(@"
        };

        /// <summary>
        /// Checksum algorithms supported by this operation for response validation
        /// </summary>
        protected override System.Collections.ObjectModel.ReadOnlyCollection<CoreChecksumAlgorithm> ChecksumResponseAlgorithms => _supportedChecksumAlgorithms.AsReadOnly();
#endregion
");
            
            #line 511 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"

                }

                if (this.Structure.Members.Any(m => !m.IsExcluded && m.IsBackwardsCompatibleDateTimeProperty))
                {

            
            #line default
            #line hidden
            this.Write("#region Backwards compatible properties\r\n");
            
            #line 518 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"

                    foreach(var member in this.Structure.Members)
                    {
                        if (member.IsExcluded || !member.IsBackwardsCompatibleDateTimeProperty)
                            continue;

            
            #line default
            #line hidden
            this.Write("        private ");
            
            #line 524 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.DetermineType()));
            
            #line default
            #line hidden
            
            #line 524 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.IsNullable ? "?" : ""));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 524 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.BackwardCompatibilityVariableName));
            
            #line default
            #line hidden
            
            #line 524 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.ShouldInstantiate ? string.Format(" = new {0}();", member.DetermineType()) : ";"));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 525 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"

                    }

            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 529 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"

                    foreach(var member in this.Structure.Members)
                    {
                        if (member.IsExcluded || !member.IsBackwardsCompatibleDateTimeProperty)
                            continue;

            
            #line default
            #line hidden
            
            #line 535 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"
 this.FormatPropertyDocumentation(member, "This property is deprecated. Setting this property results in non-UTC DateTimes " +
        "not being marshalled correctly. Use " + member.PropertyName + " instead. Setting either " + member.BackwardCompatibilityPropertyName +
        " or " + member.PropertyName + " results in both " + member.BackwardCompatibilityPropertyName + " and " + 
        member.PropertyName + " being assigned, the latest assignment to either one of the two property is reflected in " +
        "the value of both. " + member.BackwardCompatibilityPropertyName + " is provided for backwards compatibility only " +
        "and assigning a non-Utc DateTime to it results in the wrong timestamp being passed to the service.");
            
            #line default
            #line hidden
            this.Write("        [Obsolete(\"Setting this property results in non-UTC DateTimes not being m" +
                    "arshalled correctly. \" +\r\n            \"Use ");
            
            #line 542 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.PropertyName));
            
            #line default
            #line hidden
            this.Write(" instead. Setting either ");
            
            #line 542 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.BackwardCompatibilityPropertyName));
            
            #line default
            #line hidden
            this.Write(" or ");
            
            #line 542 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.PropertyName));
            
            #line default
            #line hidden
            this.Write(" results in both ");
            
            #line 542 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.BackwardCompatibilityPropertyName));
            
            #line default
            #line hidden
            this.Write(" and \" +\r\n            \"");
            
            #line 543 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.PropertyName));
            
            #line default
            #line hidden
            this.Write(" being assigned, the latest assignment to either one of the two property is \" + \r" +
                    "\n            \"reflected in the value of both. ");
            
            #line 544 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.BackwardCompatibilityPropertyName));
            
            #line default
            #line hidden
            this.Write(" is provided for backwards compatibility only and \" +\r\n            \"assigning a n" +
                    "on-Utc DateTime to it results in the wrong timestamp being passed to the service" +
                    ".\", false)]\r\n        ");
            
            #line 546 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.AccessModifier));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 546 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.DetermineType()));
            
            #line default
            #line hidden
            
            #line 546 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.UseNullable ? "?" : ""));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 546 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.BackwardCompatibilityPropertyName));
            
            #line default
            #line hidden
            this.Write("\r\n        {\r\n            get { return this.");
            
            #line 548 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.BackwardCompatibilityVariableName));
            
            #line default
            #line hidden
            this.Write(".GetValueOrDefault(); }\r\n            set\r\n            {\r\n                this.");
            
            #line 551 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.BackwardCompatibilityVariableName));
            
            #line default
            #line hidden
            this.Write(" = value;\r\n                this.");
            
            #line 552 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.VariableName));
            
            #line default
            #line hidden
            this.Write(" = new DateTime(value.Ticks, DateTimeKind.Utc);\r\n            }\r\n        }\r\n");
            
            #line 555 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"

                        if (member.EmitIsSetProperties)
                        {

            
            #line default
            #line hidden
            this.Write("        /// <summary>\r\n        /// This property is set to true if the property <" +
                    "seealso cref=\"");
            
            #line 560 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.BackwardCompatibilityPropertyName));
            
            #line default
            #line hidden
            this.Write(@"""/>
        /// is set; false otherwise.
        /// This property can be used to determine if the related property
        /// was returned by a service response or if the related property
        /// should be sent to the service during a service call.
        /// </summary>
        /// <returns>
        /// True if the related property was set or will be sent to a service; false otherwise.
        /// </returns>
        [Obsolete(""Setting ");
            
            #line 569 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.BackwardCompatibilityPropertyName));
            
            #line default
            #line hidden
            this.Write(" results in non-UTC DateTimes not being marshalled correctly. Use ");
            
            #line 569 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.PropertyName));
            
            #line default
            #line hidden
            this.Write(" instead.\", false)]\r\n        public bool Is");
            
            #line 570 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.BackwardCompatibilityPropertyName));
            
            #line default
            #line hidden
            this.Write("Set\r\n        {\r\n            get\r\n            {\r\n                return this.Is");
            
            #line 574 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.PropertyName));
            
            #line default
            #line hidden
            this.Write("Set;\r\n            }\r\n            set\r\n            {\r\n                this.Is");
            
            #line 578 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.PropertyName));
            
            #line default
            #line hidden
            this.Write("Set = value;;\r\n            }\r\n        }\r\n");
            
            #line 581 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"

                        }
                    }


            
            #line default
            #line hidden
            this.Write("#endregion\r\n");
            
            #line 587 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"

                }
                if (this.Structure is ExceptionShape)
                {
                    var exceptionShape = (ExceptionShape)this.Structure;
                    if (exceptionShape.IsRetryable)
                    {

            
            #line default
            #line hidden
            this.Write(@"        /// <summary>
        /// Flag indicating if the exception is retryable and the associated retry
        /// details. A null value indicates that the exception is not retryable.
        /// </summary>
        public override RetryableDetails Retryable
        {
            get
            {
                return _retryableDetails;
            }
        }
");
            
            #line 606 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"

                    }
                }
            }

        }
        else //TODO: remove this else clause. It was added just to preserve whitespaces
        {

            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 616 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"

        }
        if (this.StructureType == StructureType.Response && hasStreamingMember) 
        {

            
            #line default
            #line hidden
            this.Write(@"        #region Dispose Pattern

        private bool _disposed;

        /// <summary>
        /// Disposes of all managed and unmanaged resources.
        /// </summary>
        public void Dispose()
        {
            Dispose(true);
            GC.SuppressFinalize(this);
        }

        protected virtual void Dispose(bool disposing)
        {
            if (_disposed)
                return;

            if (disposing)
            {
");
            
            #line 641 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"

                if (this.Structure != null) 
                {
                    foreach (var member in this.Structure.Members) 
                    {
                        if (member.IsStreaming) 
                        {

            
            #line default
            #line hidden
            this.Write("                this.");
            
            #line 649 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.VariableName));
            
            #line default
            #line hidden
            this.Write("?.Dispose();\r\n                this.");
            
            #line 650 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.VariableName));
            
            #line default
            #line hidden
            this.Write(" = null;\r\n");
            
            #line 651 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"

                        }
                    }
                }

            
            #line default
            #line hidden
            this.Write("            }\r\n\r\n            this._disposed = true;\r\n         }\r\n\r\n         #endr" +
                    "egion\r\n");
            
            #line 662 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"

        }

            
            #line default
            #line hidden
            this.Write("    }\r\n}\r\n\r\n\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 669 "C:\Dev\Repos\AWSDotNetPublic\generator\ServiceClientGeneratorLib\Generators\SourceFiles\StructureGenerator.tt"

    // Set to true when the service model specifies a shape that should be wrapped in a response. ElastiCache CreateCacheCluster is an example of this.
    public bool IsWrapped { get; set; }

    public Operation Operation { get; set; }
    public string ClassName { get; set; }
    public string BaseClass { get; set; }
    public Shape Structure { get; set; }
    public StructureType StructureType { get; set; }

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
}
