// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 12.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ServiceClientGenerator.Generators
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\code\dotnet\release-merging\sdk\src\ServiceClientGenerator\Generators\AWSQueryEC2ResponseUnmarshaller.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "12.0.0.0")]
    public partial class AWSQueryEC2ResponseUnmarshaller : BaseResponseUnmarshaller
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 6 "C:\code\dotnet\release-merging\sdk\src\ServiceClientGenerator\Generators\AWSQueryEC2ResponseUnmarshaller.tt"

    AddLicenseHeader();

    AddCommonUsingStatements();

            
            #line default
            #line hidden
            this.Write("namespace ");
            
            #line 11 "C:\code\dotnet\release-merging\sdk\src\ServiceClientGenerator\Generators\AWSQueryEC2ResponseUnmarshaller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Config.Namespace));
            
            #line default
            #line hidden
            this.Write(".Model.Internal.MarshallTransformations\r\n{\r\n    /// <summary>\r\n    /// Response U" +
                    "nmarshaller for ");
            
            #line 14 "C:\code\dotnet\release-merging\sdk\src\ServiceClientGenerator\Generators\AWSQueryEC2ResponseUnmarshaller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.UnmarshallerBaseName));
            
            #line default
            #line hidden
            this.Write(" operation\r\n    /// </summary>  \r\n    public class ");
            
            #line 16 "C:\code\dotnet\release-merging\sdk\src\ServiceClientGenerator\Generators\AWSQueryEC2ResponseUnmarshaller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.UnmarshallerBaseName));
            
            #line default
            #line hidden
            this.Write("ResponseUnmarshaller : EC2ResponseUnmarshaller\r\n    {\r\n        public override Am" +
                    "azonWebServiceResponse Unmarshall(XmlUnmarshallerContext context)\r\n        {\r\n  " +
                    "          ");
            
            #line 20 "C:\code\dotnet\release-merging\sdk\src\ServiceClientGenerator\Generators\AWSQueryEC2ResponseUnmarshaller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.UnmarshallerBaseName));
            
            #line default
            #line hidden
            this.Write("Response response = new ");
            
            #line 20 "C:\code\dotnet\release-merging\sdk\src\ServiceClientGenerator\Generators\AWSQueryEC2ResponseUnmarshaller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Operation.Name));
            
            #line default
            #line hidden
            this.Write("Response();\r\n\r\n");
            
            #line 22 "C:\code\dotnet\release-merging\sdk\src\ServiceClientGenerator\Generators\AWSQueryEC2ResponseUnmarshaller.tt"
 if (this.HasSuppressedResult)
   {

            
            #line default
            #line hidden
            this.Write("            while (context.Read())\r\n            {\r\n\t\t\t\r\n\t\t\t}\r\n");
            
            #line 29 "C:\code\dotnet\release-merging\sdk\src\ServiceClientGenerator\Generators\AWSQueryEC2ResponseUnmarshaller.tt"

   }
   else
   {

            
            #line default
            #line hidden
            this.Write(@"            int originalDepth = context.CurrentDepth;
            int targetDepth = originalDepth + 1;
            if (context.IsStartOfDocument) 
               targetDepth = 2;

            while (context.ReadAtDepth(originalDepth))
            {
                if (context.IsStartElement || context.IsAttribute)
                {

");
            
            #line 44 "C:\code\dotnet\release-merging\sdk\src\ServiceClientGenerator\Generators\AWSQueryEC2ResponseUnmarshaller.tt"

		if(this.Structure != null)
		{
			if(this.IsWrapped)
			{

            
            #line default
            #line hidden
            this.Write("                    if ( context.TestExpression(\".\", targetDepth))\r\n             " +
                    "       {\r\n                        response.");
            
            #line 52 "C:\code\dotnet\release-merging\sdk\src\ServiceClientGenerator\Generators\AWSQueryEC2ResponseUnmarshaller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(MemberAccessorFor(this.Structure.Name)));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 52 "C:\code\dotnet\release-merging\sdk\src\ServiceClientGenerator\Generators\AWSQueryEC2ResponseUnmarshaller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Structure.Name));
            
            #line default
            #line hidden
            this.Write("Unmarshaller.Instance.Unmarshall(context);\r\n                        continue;\r\n  " +
                    "                  }\r\n");
            
            #line 55 "C:\code\dotnet\release-merging\sdk\src\ServiceClientGenerator\Generators\AWSQueryEC2ResponseUnmarshaller.tt"
 
			}
			else
			{
				foreach (var member in this.Structure.Members)
				{
					var testExpression= GeneratorHelpers.DetermineAWSQueryTestExpression(member);

            
            #line default
            #line hidden
            this.Write("                    if (context.TestExpression(\"");
            
            #line 63 "C:\code\dotnet\release-merging\sdk\src\ServiceClientGenerator\Generators\AWSQueryEC2ResponseUnmarshaller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(testExpression));
            
            #line default
            #line hidden
            this.Write("\", targetDepth))\r\n                    {\r\n                        var unmarshaller" +
                    " = ");
            
            #line 65 "C:\code\dotnet\release-merging\sdk\src\ServiceClientGenerator\Generators\AWSQueryEC2ResponseUnmarshaller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.DetermineTypeUnmarshallerInstantiate()));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 66 "C:\code\dotnet\release-merging\sdk\src\ServiceClientGenerator\Generators\AWSQueryEC2ResponseUnmarshaller.tt"

					if (member.IsList)
					{

            
            #line default
            #line hidden
            this.Write("                        var item = unmarshaller.Unmarshall(context);\r\n           " +
                    "             response.");
            
            #line 71 "C:\code\dotnet\release-merging\sdk\src\ServiceClientGenerator\Generators\AWSQueryEC2ResponseUnmarshaller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(MemberAccessorFor(member.PropertyName)));
            
            #line default
            #line hidden
            this.Write(".Add(item);\r\n");
            
            #line 72 "C:\code\dotnet\release-merging\sdk\src\ServiceClientGenerator\Generators\AWSQueryEC2ResponseUnmarshaller.tt"

					}
					else
					{

            
            #line default
            #line hidden
            this.Write("                        response.");
            
            #line 77 "C:\code\dotnet\release-merging\sdk\src\ServiceClientGenerator\Generators\AWSQueryEC2ResponseUnmarshaller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(MemberAccessorFor(member.PropertyName)));
            
            #line default
            #line hidden
            this.Write(" = unmarshaller.Unmarshall(context);\r\n");
            
            #line 78 "C:\code\dotnet\release-merging\sdk\src\ServiceClientGenerator\Generators\AWSQueryEC2ResponseUnmarshaller.tt"

	                }

            
            #line default
            #line hidden
            this.Write("                        continue;\r\n                    }\r\n");
            
            #line 83 "C:\code\dotnet\release-merging\sdk\src\ServiceClientGenerator\Generators\AWSQueryEC2ResponseUnmarshaller.tt"

				}
			}
		}

            
            #line default
            #line hidden
            this.Write("                } \r\n            }\r\n");
            
            #line 90 "C:\code\dotnet\release-merging\sdk\src\ServiceClientGenerator\Generators\AWSQueryEC2ResponseUnmarshaller.tt"

	}

            
            #line default
            #line hidden
            this.Write(@"
            return response;
        }

        public override AmazonServiceException UnmarshallException(XmlUnmarshallerContext context, Exception innerException, HttpStatusCode statusCode)
        {
            ErrorResponse errorResponse = ErrorResponseUnmarshaller.GetInstance().Unmarshall(context);
");
            
            #line 100 "C:\code\dotnet\release-merging\sdk\src\ServiceClientGenerator\Generators\AWSQueryEC2ResponseUnmarshaller.tt"

    foreach (var exception in this.Operation.Exceptions)
    {

            
            #line default
            #line hidden
            this.Write("            if (errorResponse.Code != null && errorResponse.Code.Equals(\"");
            
            #line 104 "C:\code\dotnet\release-merging\sdk\src\ServiceClientGenerator\Generators\AWSQueryEC2ResponseUnmarshaller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(exception.Code));
            
            #line default
            #line hidden
            this.Write("\"))\r\n            {\r\n                return new ");
            
            #line 106 "C:\code\dotnet\release-merging\sdk\src\ServiceClientGenerator\Generators\AWSQueryEC2ResponseUnmarshaller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(exception.Name));
            
            #line default
            #line hidden
            this.Write("(errorResponse.Message, innerException, errorResponse.Type, errorResponse.Code, e" +
                    "rrorResponse.RequestId, statusCode);\r\n            }\r\n");
            
            #line 108 "C:\code\dotnet\release-merging\sdk\src\ServiceClientGenerator\Generators\AWSQueryEC2ResponseUnmarshaller.tt"

    }

            
            #line default
            #line hidden
            this.Write("            return new Amazon");
            
            #line 111 "C:\code\dotnet\release-merging\sdk\src\ServiceClientGenerator\Generators\AWSQueryEC2ResponseUnmarshaller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Config.BaseName));
            
            #line default
            #line hidden
            this.Write("Exception(errorResponse.Message, innerException, errorResponse.Type, errorRespons" +
                    "e.Code, errorResponse.RequestId, statusCode);\r\n        }\r\n");
            
            #line 113 "C:\code\dotnet\release-merging\sdk\src\ServiceClientGenerator\Generators\AWSQueryEC2ResponseUnmarshaller.tt"

	    this.AddResponseSingletonMethod();

            
            #line default
            #line hidden
            this.Write("    }\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 118 "C:\code\dotnet\release-merging\sdk\src\ServiceClientGenerator\Generators\AWSQueryEC2ResponseUnmarshaller.tt"

// if the result fields have been wrapped in a subordinate structure, wire the accessor
// to use it when addressing a member
string MemberAccessorFor(string memberName)
{
	return string.IsNullOrEmpty(WrappedResultMember) ? memberName : WrappedResultMember;
}	

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
}
