using Amazon.DynamoDBv2;
using Amazon.DynamoDBv2.DataModel;
using System;
using System.Collections.Generic;
using System.IO;

namespace AWSSDK_DotNet.IntegrationTests.Tests.DynamoDB
{
    /// <summary>
    /// Class representing items in the table [TableNamePrefix]HashTable
    /// </summary>
    [DynamoDBTable("HashTable")]
    public class Product
    {
        [DynamoDBHashKey] public int Id { get; set; }

        [DynamoDBProperty("Product")] public string Name { get; set; }

        [DynamoDBGlobalSecondaryIndexHashKey("GlobalIndex", AttributeName = "Company")]
        public string CompanyName { get; set; }

        public CompanyInfo CompanyInfo { get; set; }

        [DynamoDBGlobalSecondaryIndexRangeKey("GlobalIndex")]
        public int Price { get; set; }

        [DynamoDBProperty("Tags")] public HashSet<string> TagSet { get; set; }

        public MemoryStream Data { get; set; }

        [DynamoDBProperty(Converter = typeof(StatusConverter))]
        public Status CurrentStatus { get; set; }

        public Status FormerStatus { get; set; }

        public Support Supports { get; set; }

        public Support? PreviousSupport { get; set; }

        [DynamoDBIgnore] public string InternalId { get; set; }

        public bool IsPublic { get; set; }

        public bool AlwaysN { get; set; }

        public int? Rating { get; set; }

        public List<string> Components { get; set; }

        [DynamoDBProperty(Converter = typeof(ListToSetPropertyConverter<byte>))]
        public List<byte> KeySizes { get; set; }

        public Dictionary<string, string> Map { get; set; }

        public S3Link FullProductDescription { get; set; }
    }

    [DynamoDBTable("HashTable", false, ConversionSchema.V2)]
    public class ProductV2 : Product
    {
    }

    public class CompanyInfo
    {
        public string Name { get; set; }
        public DateTime Founded { get; set; }
        public Product MostPopularProduct { get; set; }
        public List<Product> AllProducts { get; set; }
        public Product[] FeaturedProducts { get; set; }
        public string[] FeaturedBrands { get; set; }
        public Dictionary<string, List<Product>> CompetitorProducts { get; set; }

        [DynamoDBIgnore] public decimal Revenue { get; set; }
    }

    /// <summary>
    /// Class representing items in the table [TableNamePrefix]HashTable
    /// This class uses optimistic locking via the Version field
    /// </summary>
    public class VersionedProduct : Product
    {
        [DynamoDBVersion] public int? Version { get; set; }
    }

    /// <summary>
    /// Class representing items in the table [TableNamePrefix]HashTable,
    /// with the Id field being an Enum, with hidden int conversion
    /// </summary>
    [DynamoDBTable("HashTable")]
    public class EnumProduct1
    {
        [DynamoDBIgnore] public Status Id { get; set; }

        [DynamoDBHashKey("Id")]
        public int IdAsInt
        {
            get { return (int)Id; }
            set { Id = (Status)value; }
        }

        [DynamoDBProperty("Product")] public string Name { get; set; }
    }

    /// <summary>
    /// Class representing items in the table [TableNamePrefix]HashTable,
    /// with the Id field being an Enum
    /// </summary>
    [DynamoDBTable("HashTable")]
    public class EnumProduct2
    {
        public Status Id { get; set; }

        [DynamoDBProperty("Product")] public string Name { get; set; }
    }

    /// <summary>
    /// A class has a flattened property, and the version attribute is on the flattened child.
    /// </summary>
    [DynamoDBTable("HashTable")]
    public class ProductFlat
    {
        [DynamoDBHashKey] public int Id { get; set; }

        [DynamoDBFlatten]
        public ProductDetails Details { get; set; }

        public string Name { get; set; }
    }

    public class ProductDetails
    {
        [DynamoDBVersion]
        public int? Version { get; set; }

        public string Description { get; set; }

        [DynamoDBProperty("DetailsName")]
        public string Name { get; set; }
    }

    [DynamoDBTable("HashTable")]
    public class ProductFlatWithTimestamp
    {
        [DynamoDBHashKey] public int Id { get; set; }
        [DynamoDBFlatten] public ProductDetailsWithTimestamp Details { get; set; }
        public string Name { get; set; }
    }

    public class ProductDetailsWithTimestamp
    {
        [DynamoDBVersion] public int? Version { get; set; }
        [DynamoDBAutoGeneratedTimestamp] public DateTime? CreatedAt { get; set; }
        public string Description { get; set; }
        [DynamoDBProperty("DetailsName")] public string Name { get; set; }
    }

    [DynamoDBTable("HashTable")]
    public class ProductFlatWithAtomicCounter
    {
        [DynamoDBHashKey] public int Id { get; set; }
        [DynamoDBFlatten] public ProductDetailsWithAtomicCounter Details { get; set; }
        public string Name { get; set; }
    }

    public class ProductDetailsWithAtomicCounter
    {
        [DynamoDBVersion] public int? Version { get; set; }
        [DynamoDBAtomicCounter] public int? CountDefault { get; set; }
        [DynamoDBAtomicCounter(delta: 2, startValue: 10)] public int? CountAtomic { get; set; }
        public string Description { get; set; }
        [DynamoDBProperty("DetailsName")] public string Name { get; set; }
    }

    [DynamoDBTable("HashTable")]
    public class ProductWithCreateTimestamp
    {
        [DynamoDBHashKey] public int Id { get; set; }
        public string Name { get; set; }
        [DynamoDBAutoGeneratedTimestamp]
        [DynamoDbUpdateBehavior(UpdateBehavior.IfNotExists)]
        public DateTime? CreatedAt { get; set; }
    }

    [DynamoDBTable("HashTable")]
    public class AutoGenTimestampEpochEntity
    {
        [DynamoDBHashKey]
        public int Id { get; set; }

        public string Name { get; set; }

        [DynamoDBAutoGeneratedTimestamp]
        [DynamoDbUpdateBehavior(UpdateBehavior.IfNotExists)]
        [DynamoDBProperty(StoreAsEpoch = true)]
        public DateTime? CreatedAt { get; set; }

        [DynamoDBAutoGeneratedTimestamp]
        [DynamoDBProperty(StoreAsEpoch = true)]
        public DateTime? UpdatedAt { get; set; }
    }

    [DynamoDBTable("HashTable")]
    public class AutoGenTimestampEpochLongEntity
    {
        [DynamoDBHashKey]
        public int Id { get; set; }

        public string Name { get; set; }

        [DynamoDBAutoGeneratedTimestamp]
        [DynamoDbUpdateBehavior(UpdateBehavior.IfNotExists)]
        [DynamoDBProperty(StoreAsEpochLong = true)]
        public DateTime? CreatedAt { get; set; }

        [DynamoDBProperty(StoreAsEpochLong = true)]
        public DateTime? CreatedAt1 { get; set; }

        [DynamoDBAutoGeneratedTimestamp]
        [DynamoDBProperty(StoreAsEpochLong = true)]
        public DateTime? UpdatedAt { get; set; }
    }
}
