# Apply potential regression label on issues
name: issue-regression-label
on:
  issues:
    types: [opened, edited]
permissions: {}
concurrency:
  group: ${{ github.workflow }}-${{ github.event.issue.number }}
  cancel-in-progress: true
jobs:
  add-regression-label:
    name: Add potential-regression label
    runs-on: ubuntu-latest
    permissions:
      issues: write # to add or remove the potential-regression label
    steps:
    - name: Fetch template body
      id: check_regression
      uses: actions/github-script@f28e40c7f34bde8b3046d885e986cb6290c5673b # v7.1.0
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TEMPLATE_BODY: ${{ github.event.issue.body }}
      with:
        script: |
          const regressionPattern = /\[x\] Select this option if this issue appears to be a regression\./i;
          const template = `${process.env.TEMPLATE_BODY}`
          const match = regressionPattern.test(template);
          core.setOutput('is_regression', match);
    - name: Manage regression label
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        IS_REGRESSION: ${{ steps.check_regression.outputs.is_regression }}
        ISSUE_NUMBER: ${{ github.event.issue.number }}
      run: |
        if [ "$IS_REGRESSION" == "true" ]; then
          gh issue edit "$ISSUE_NUMBER" --add-label "potential-regression" -R "$GITHUB_REPOSITORY"
        else
          gh issue edit "$ISSUE_NUMBER" --remove-label "potential-regression" -R "$GITHUB_REPOSITORY"
        fi
