name: Build SDK V4
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - development

concurrency:
  group: build-sdk-v4-${{ github.ref }}
  cancel-in-progress: true

env:
  # constants
  DOWNLOAD_FOLDER: '.build-scripts/'
  SCRIPT_LOCATION: 'workflows/start-pull-request-build/pull-request-build-v1.sh'

  # custom variables
  IAM_ROLE_ARN: 'arn:aws:iam::767397770662:role/AwsSdkNetGitHubRole'

jobs:
  build-sdk-v4:
    # Skip draft PRs and PRs from forked repos (they don't have access)
    if: github.event.pull_request.draft == false && github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      issues: write
      pull-requests: write
      contents: read
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@main
        with:
          role-to-assume: 'arn:aws:iam::767397770662:role/AwsSdkNetGitHubRole'
          role-session-name: PullRequestBuildGitHubAction
          role-duration-seconds: 9000
          aws-region: us-west-2
      - name: Download Build Script
        run: |
          aws s3 cp s3://aws-sdk-builds-github-assets-prod-us-west-2/$SCRIPT_LOCATION ./$DOWNLOAD_FOLDER/$SCRIPT_LOCATION --no-progress
          chmod +x ./$DOWNLOAD_FOLDER/$SCRIPT_LOCATION
      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          HEAD_REF: ${{ github.event.pull_request.head.ref }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          RUN_ID: ${{ github.run_id }}
        run: |
          ./$DOWNLOAD_FOLDER/$SCRIPT_LOCATION \
            --repo "$REPO" \
            --branch "$HEAD_REF" \
            --pr-number "$PR_NUMBER" \
            --run-id "$RUN_ID"
        timeout-minutes: 150
